name: Keep Streamlit App Awake

on:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Curl your Streamlit app
        run: curl -s --head https://nikhilgupta.streamlit.app || true