name: Keep Streamlit App Awake

on:
  schedule:
    - cron: '*/28 * * * *'
  workflow_dispatch:

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Wake and ping app with retries
        run: |
          echo "Pinging Streamlit app..."

          curl -sSfL \
            --retry 3 \
            --retry-delay 10 \
            --retry-max-time 60 \
            --max-time 30 \
            -H "Cache-Control: no-cache" \
            "https://nikhilgupta.streamlit.app" || echo "Ping failed"

          echo "Ping completed at $(date)"
